export const themes = {
  blue: {
    name: "Blue",
    primary: "bg-blue-500 hover:bg-blue-600",
    primaryText: "text-blue-500",
    primaryBorder: "border-blue-500",
    primaryHover: "hover:bg-blue-100 hover:text-blue-600 hover:border-blue-300",
    gradient: "from-blue-500 to-cyan-400",
    background: "from-blue-100 via-cyan-50 to-blue-200",
    headerBg: "bg-gradient-to-r from-blue-600 to-cyan-500",
    headerBorder: "border-blue-400",
    sliderBg: "bg-blue-600",
    accent: "bg-blue-200 text-blue-700",
    ring: "focus:ring-blue-400 focus:border-blue-400",
    icon: "🔵",
  },
  purple: {
    name: "Purple",
    primary: "bg-purple-500 hover:bg-purple-600",
    primaryText: "text-purple-500",
    primaryBorder: "border-purple-500",
    primaryHover: "hover:bg-purple-100 hover:text-purple-600 hover:border-purple-300",
    gradient: "from-purple-500 to-pink-400",
    background: "from-purple-100 via-pink-50 to-purple-200",
    headerBg: "bg-gradient-to-r from-purple-600 to-pink-500",
    headerBorder: "border-purple-400",
    sliderBg: "bg-purple-600",
    accent: "bg-purple-200 text-purple-700",
    ring: "focus:ring-purple-400 focus:border-purple-400",
    icon: "🟣",
  },
  green: {
    name: "Green",
    primary: "bg-green-500 hover:bg-green-600",
    primaryText: "text-green-500",
    primaryBorder: "border-green-500",
    primaryHover: "hover:bg-green-100 hover:text-green-600 hover:border-green-300",
    gradient: "from-green-500 to-emerald-400",
    background: "from-green-100 via-emerald-50 to-green-200",
    headerBg: "bg-gradient-to-r from-green-600 to-emerald-500",
    headerBorder: "border-green-400",
    sliderBg: "bg-green-600",
    accent: "bg-green-200 text-green-700",
    ring: "focus:ring-green-400 focus:border-green-400",
    icon: "🟢",
  },
  orange: {
    name: "Orange",
    primary: "bg-orange-500 hover:bg-orange-600",
    primaryText: "text-orange-500",
    primaryBorder: "border-orange-500",
    primaryHover: "hover:bg-orange-100 hover:text-orange-600 hover:border-orange-300",
    gradient: "from-orange-500 to-yellow-400",
    background: "from-orange-100 via-yellow-50 to-orange-200",
    headerBg: "bg-gradient-to-r from-orange-600 to-yellow-500",
    headerBorder: "border-orange-400",
    sliderBg: "bg-orange-600",
    accent: "bg-orange-200 text-orange-700",
    ring: "focus:ring-orange-400 focus:border-orange-400",
    icon: "🟠",
  },
  pink: {
    name: "Pink",
    primary: "bg-pink-500 hover:bg-pink-600",
    primaryText: "text-pink-500",
    primaryBorder: "border-pink-500",
    primaryHover: "hover:bg-pink-100 hover:text-pink-600 hover:border-pink-300",
    gradient: "from-pink-500 to-rose-400",
    background: "from-pink-100 via-rose-50 to-pink-200",
    headerBg: "bg-gradient-to-r from-pink-600 to-rose-500",
    headerBorder: "border-pink-400",
    sliderBg: "bg-pink-600",
    accent: "bg-pink-200 text-pink-700",
    ring: "focus:ring-pink-400 focus:border-pink-400",
    icon: "🩷",
  },
  rainbow: {
    name: "Rainbow",
    primary: "bg-gradient-to-r from-pink-500 to-violet-500 hover:from-pink-600 hover:to-violet-600",
    primaryText: "text-violet-500",
    primaryBorder: "border-violet-500",
    primaryHover:
      "hover:bg-gradient-to-r hover:from-pink-100 hover:to-violet-100 hover:text-violet-600 hover:border-violet-300",
    gradient: "from-pink-500 via-purple-500 to-violet-500",
    background: "from-pink-100 via-purple-50 to-violet-100",
    headerBg: "bg-gradient-to-r from-pink-600 via-purple-600 to-violet-600",
    headerBorder: "border-purple-400",
    sliderBg: "bg-gradient-to-r from-pink-500 to-pink-600",
    accent: "bg-gradient-to-r from-pink-200 to-violet-200 text-violet-700",
    ring: "focus:ring-violet-400 focus:border-violet-400",
    icon: "🌈",
  },
  // 新增的6种配色
  red: {
    name: "Red",
    primary: "bg-red-500 hover:bg-red-600",
    primaryText: "text-red-500",
    primaryBorder: "border-red-500",
    primaryHover: "hover:bg-red-100 hover:text-red-600 hover:border-red-300",
    gradient: "from-red-500 to-orange-400",
    background: "from-red-100 via-orange-50 to-red-200",
    headerBg: "bg-gradient-to-r from-red-600 to-orange-500",
    headerBorder: "border-red-400",
    sliderBg: "bg-red-600",
    accent: "bg-red-200 text-red-700",
    ring: "focus:ring-red-400 focus:border-red-400",
    icon: "🔴",
  },
  cyan: {
    name: "Cyan",
    primary: "bg-cyan-500 hover:bg-cyan-600",
    primaryText: "text-cyan-500",
    primaryBorder: "border-cyan-500",
    primaryHover: "hover:bg-cyan-100 hover:text-cyan-600 hover:border-cyan-300",
    gradient: "from-cyan-500 to-blue-400",
    background: "from-cyan-100 via-blue-50 to-cyan-200",
    headerBg: "bg-gradient-to-r from-cyan-600 to-blue-500",
    headerBorder: "border-cyan-400",
    sliderBg: "bg-cyan-600",
    accent: "bg-cyan-200 text-cyan-700",
    ring: "focus:ring-cyan-400 focus:border-cyan-400",
    icon: "🔷",
  },
  yellow: {
    name: "Yellow",
    primary: "bg-yellow-500 hover:bg-yellow-600",
    primaryText: "text-yellow-600",
    primaryBorder: "border-yellow-500",
    primaryHover: "hover:bg-yellow-100 hover:text-yellow-700 hover:border-yellow-400",
    gradient: "from-yellow-400 to-amber-400",
    background: "from-yellow-100 via-amber-50 to-yellow-200",
    headerBg: "bg-gradient-to-r from-yellow-500 to-amber-500",
    headerBorder: "border-yellow-400",
    sliderBg: "bg-yellow-500",
    accent: "bg-yellow-200 text-yellow-800",
    ring: "focus:ring-yellow-400 focus:border-yellow-400",
    icon: "🟡",
  },
  indigo: {
    name: "Indigo",
    primary: "bg-indigo-500 hover:bg-indigo-600",
    primaryText: "text-indigo-500",
    primaryBorder: "border-indigo-500",
    primaryHover: "hover:bg-indigo-100 hover:text-indigo-600 hover:border-indigo-300",
    gradient: "from-indigo-500 to-purple-400",
    background: "from-indigo-100 via-purple-50 to-indigo-200",
    headerBg: "bg-gradient-to-r from-indigo-600 to-purple-500",
    headerBorder: "border-indigo-400",
    sliderBg: "bg-indigo-600",
    accent: "bg-indigo-200 text-indigo-700",
    ring: "focus:ring-indigo-400 focus:border-indigo-400",
    icon: "🟦",
  },
  teal: {
    name: "Teal",
    primary: "bg-teal-500 hover:bg-teal-600",
    primaryText: "text-teal-500",
    primaryBorder: "border-teal-500",
    primaryHover: "hover:bg-teal-100 hover:text-teal-600 hover:border-teal-300",
    gradient: "from-teal-500 to-green-400",
    background: "from-teal-100 via-green-50 to-teal-200",
    headerBg: "bg-gradient-to-r from-teal-600 to-green-500",
    headerBorder: "border-teal-400",
    sliderBg: "bg-teal-600",
    accent: "bg-teal-200 text-teal-700",
    ring: "focus:ring-teal-400 focus:border-teal-400",
    icon: "🟩",
  },
  rose: {
    name: "Rose",
    primary: "bg-rose-500 hover:bg-rose-600",
    primaryText: "text-rose-500",
    primaryBorder: "border-rose-500",
    primaryHover: "hover:bg-rose-100 hover:text-rose-600 hover:border-rose-300",
    gradient: "from-rose-500 to-pink-400",
    background: "from-rose-100 via-pink-50 to-rose-200",
    headerBg: "bg-gradient-to-r from-rose-600 to-pink-500",
    headerBorder: "border-rose-400",
    sliderBg: "bg-rose-600",
    accent: "bg-rose-200 text-rose-700",
    ring: "focus:ring-rose-400 focus:border-rose-400",
    icon: "🌹",
  },
} as const

export type ThemeKey = keyof typeof themes
export type Theme = (typeof themes)[ThemeKey]

export const defaultTheme: ThemeKey = "blue"
