// config/languages.ts
export type Language = {
  code: string;      // 语言代码
  name: string;      // 国家/语言名称（英文）
  flag: string;      // 国旗 emoji
};

export const languages: Language[] = [
  { code: 'zh', name: 'China', flag: '🇨🇳' },
  { code: 'en', name: 'United States', flag: '🇺🇸' },
  { code: 'es', name: 'Spain', flag: '🇪🇸' },
  { code: 'fr', name: 'France', flag: '🇫🇷' },
  { code: 'de', name: 'Germany', flag: '🇩🇪' },
  { code: 'ja', name: 'Japan', flag: '🇯🇵' },
  { code: 'ko', name: 'South Korea', flag: '🇰🇷' },
  { code: 'it', name: 'Italy', flag: '🇮🇹' },
  { code: 'pt', name: 'Brazil', flag: '🇧🇷' },
  { code: 'ru', name: 'Russia', flag: '🇷🇺' },
  { code: 'ar', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'nl', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'sv', name: 'Sweden', flag: '🇸🇪' },
  { code: 'pl', name: 'Poland', flag: '🇵🇱' },
  { code: 'tr', name: 'Turkey', flag: '🇹🇷' },
  { code: 'hi', name: 'India', flag: '🇮🇳' },
  { code: 'th', name: 'Thailand', flag: '🇹🇭' },
  { code: 'vi', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'id', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'ms', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'tl', name: 'Philippines', flag: '🇵🇭' },
  { code: 'uk', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'el', name: 'Greece', flag: '🇬🇷' },
  { code: 'cs', name: 'Czech Republic', flag: '🇨🇿' },
  { code: 'hu', name: 'Hungary', flag: '🇭🇺' },
  { code: 'ro', name: 'Romania', flag: '🇷🇴' },
  { code: 'bg', name: 'Bulgaria', flag: '🇧🇬' },
  { code: 'hr', name: 'Croatia', flag: '🇭🇷' },
  { code: 'sk', name: 'Slovakia', flag: '🇸🇰' },
  { code: 'lt', name: 'Lithuania', flag: '🇱🇹' },
  { code: 'lv', name: 'Latvia', flag: '🇱🇻' },
  { code: 'et', name: 'Estonia', flag: '🇪🇪' },
  { code: 'fi', name: 'Finland', flag: '🇫🇮' },
  { code: 'no', name: 'Norway', flag: '🇳🇴' },
  { code: 'da', name: 'Denmark', flag: '🇩🇰' },
  { code: 'is', name: 'Iceland', flag: '🇮🇸' },
  { code: 'ga', name: 'Ireland', flag: '🇮🇪' },
  { code: 'mt', name: 'Malta', flag: '🇲🇹' },
  { code: 'sl', name: 'Slovenia', flag: '🇸🇮' },
  { code: 'cy', name: 'Wales', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { code: 'eu', name: 'Basque', flag: '🇪🇸' },
  { code: 'ca', name: 'Catalonia', flag: '🇪🇸' },
  { code: 'gl', name: 'Galicia', flag: '🇪🇸' },
  { code: 'co', name: 'Corsica', flag: '🇫🇷' },
  { code: 'af', name: 'South Africa', flag: '🇿🇦' },
  { code: 'sw', name: 'Kenya', flag: '🇰🇪' },
  { code: 'zu', name: 'Zulu', flag: '🇿🇦' },
  { code: 'am', name: 'Ethiopia', flag: '🇪🇹' },
  { code: 'fa', name: 'Iran', flag: '🇮🇷' },
];
